export const DevSkills: string[] = [
	'ReactJS',
	'AngularJS',
	'TypeScript',
	'Javascript',
	'Remix',
	'NextJS',
	'SSR',
	'Prisma',
	'PostgreSQL',
	'Node.js',
	'HTML',
	'CSS',
	'Material-UI',
	'Framer-Motion',
	'Jest',
	'Vitest',
	'Cypress',
	'Playwright',
	'TailwindCSS',
	'Azure',
	'AWS',
	'Docker',
	'VBA',
	'Scrum',
];
export const UxSkills: string[] = [
	'Figma',
	'AdobeXD',
	'Photoshop',
	'Illustrator',
	'Affinity Designer',
	'Animate',
	'After Effects',
	'Premiere Pro',
	'user tests',
	'User-Centered-Design',
	'user journey map',
	'personas',
	'accessibility',
	'red routes',
	'card sorting',
	'ideation workshops',
];
